### ISSUE TITLE
Strange problems when working with Foundation 6.5

### ISSUE THREAD

**Issue by Xiaoming94** [vue-foundation/vue-foundation#40]
When I am trying to emulate your solutions as according to your guide and what I've seen in this repo.
I am getting these compilation error:
``` 
ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                15:35:54

error  in ./src/App.vue

Module build failed: 
// Copyright Joyent, Inc. and other Node contributors.
^
      Invalid CSS after "...N THE SOFTWARE.": expected 1 selector or at-rule, was "var formatRegExp = "
      in /home/xiaoming/gitRepos/drawit-site/frontend/node_modules/util/util.js (line 1, column 1)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"includePaths":["./src/styles"],"data":"@import /"./src/styles/app/";","sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-442 13:3-17:5 14:22-450
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```
And something similar in my Vue.js application site:

![2018-06-27-15 36 17-screenshot](https://user-images.githubusercontent.com/6448975/41977713-4e5109f0-7a20-11e8-9a1b-2f3e54a653e4.png)

The project was scaffolded with vue-cli 2.9.5. I am trying to get it working with `foundation-sites: ^6.5.0`

Do you have any idea how this compilation error came to be?
